#
#  $Id$
#
#################################
#  User customizable macros	#
#################################
INCDIR		= $(PREFIX)/include/TU

OTHER_DIR	= $(HOME)/projects/HRP-5P/hrp5p-calib/include/TU

#########################
#  Macros set by mkmf	#
#########################
SUFFIX		= .idl:sC
HDRS		= idl/Img.idl idl/Cmd.idl
SRCS		=

OTHER_HDRS	= $(HDRS)
OTHER_SRCS	= $(SRCS)

include $(PROJECT)/lib/lib.mk
include $(PROJECT)/lib/common.mk
include $(PROJECT)/lib/other.mk

###
