/*
 *  $Id$
 */
#ifndef __TU_CMD_IDL
#define __TU_CMD_IDL

#include <BasicDataType.idl>

module Cmd
{
typedef sequence<long>	Values;
    
interface Controller
{
    string	getCmds()						;
    
    void	getValues(out   Values vals)				;
    void	setValues(inout Values vals)				;
};

};

#endif	/* __TU_CAM_IDL	*/
