/*
 *  $Id$
 */
#ifndef __TU_CMD_IDL
#define __TU_CMD_IDL

module Cmd
{
typedef sequence<long>	Values;
    
interface Controller
{
    string	getCmds()						;
    
    boolean	setValues(in Values vals)				;
    Values	getValues(in Values ids)				;
};

};

#endif	/* !__TU_CMD_IDL	*/
