/*
 *  $Id$
 */
#ifndef __TU_CMD_IDL
#define __TU_CMD_IDL

module Cmd
{
struct Value
{
    long	i;
    float	f;
};
    
typedef sequence<Value>		Values;
    
interface Controller
{
    string	getCmds()						;
    
    boolean	setValues(in Values vals)				;
    Values	getValues(in Values ids)				;
};

};

#endif	/* !__TU_CMD_IDL	*/
