/*
 *  $Id$
 */
#ifndef __TU_IMG_IDL
#define __TU_IMG_IDL

#include <BasicDataType.idl>

module Img
{
typedef double	Matrix34d[3][4];

enum PixelFormat
{
    MONO_8, YUV_411, YUV_422, YUV_444, RGB_24, FLT, UNKNOWN
};

struct TimedImage
{
    RTC::Time		tm;

    PixelFormat		format;
    unsigned long	width;
    unsigned long	height;
    Matrix34d		P;
    double		d1;
    double		d2;

    sequence<octet>	data;
};

typedef sequence<TimedImage>	TimedImages;

};

#endif	/* !__TU_IMG_IDL	*/
